### ISSUE TITLE
master on pty.js is broken?

### ISSUE THREAD

**Issue by nbren12** [f/atom-term2#168]
I get the following error when I try `apm install term2`. 

~~~~
> pty.js@0.2.8 install /private/var/folders/p_/vylr3h4515ggdy5zx3n4hgfr0000gn/T/apm-install-dir-115630-49704-11k9t6r/node_modules/term2/node_modules/pty.js
> node-gyp rebuild

  CXX(target) Release/obj.target/pty/src/unix/pty.o

../src/unix/pty.cc:275:9: error: no matching function for call to 'uv_async_init'
        uv_async_init(uv_default_loop(), &baton->async, AfterWaitOnPid);
        ^~~~~~~~~~~~~
/Users/noah/.atom/.node-gyp/.node-gyp/0.22.0/deps/uv/include/uv.h:743:15: note: candidate function not viable: no known conversion from 'void (uv_async_t *, int)' to 'uv_async_cb' (aka 'void (*)(uv_async_t *)') for 3rd argument
UV_EXTERN int uv_async_init(uv_loop_t*,
              ^
1 error generated.
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/p_/vylr3h4515ggdy5zx3n4hgfr0000gn/T/apm-install-dir-115630-49704-11k9t6r/node_modules/term2/node_modules/pty.js
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Darwin 14.3.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/noah/.atom/.apm/.apmrc" "--userconfig" "/Users/noah/.atom/.apmrc" "install" "/private/var/folders/p_/vylr3h4515ggdy5zx3n4hgfr0000gn/T/d-115630-49704-1gsylrj/package.tgz" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.2.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/p_/vylr3h4515ggdy5zx3n4hgfr0000gn/T/apm-install-dir-115630-49704-11k9t6r/npm-debug.log

~~~~

I was able to fix it by manually cloning atom-term2 into `~/.atom/packages` changing `atom-iterm2/package.json` to have 
     "pty.js":  "0.2.8"

Just thought yall should know.

**Comment by MoOx** [comment]
@vigo any idea why the master is being referenced in the package.json and not a specific version (with a caret range or something)?

**Comment by vigo** [comment]
@MoOx I have no clue whats going on down there :) maybe @f will help us out?

**Comment by f** [comment]
I think @MoOx solved this issue, right?

**Comment by MoOx** [comment]
Maybe with ffb196796f52664ac46b21aa481eaf339cb0806a indeed
