### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by rhkina** [f/atom-term2#172]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.179.0
**System**: linux 3.13.0-61-generic
**Thrown From**: [term2](https://github.com/webBoxio/atom-term2) package, v0.9.15
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/rhkina/.atom/packages/term2/lib/TermView.coffee:136

TypeError: undefined is not a function
  at TermView.attachResizeEvents (/home/rhkina/.atom/packages/term2/lib/TermView.coffee:136:36)
  at TermView.attachEvents (/home/rhkina/.atom/packages/term2/lib/TermView.coffee:111:6)
  at TermView.initialize (/home/rhkina/.atom/packages/term2/lib/TermView.coffee:68:6)
  at TermView.View (/usr/share/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new TermView (/home/rhkina/.atom/packages/term2/lib/TermView.coffee:36:5)
  at Object.module.exports.createTermView (/home/rhkina/.atom/packages/term2/index.coffee:137:22)
  at Object.module.exports.newTerm (/home/rhkina/.atom/packages/term2/index.coffee:175:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:65:30)
  at EventEmitter.emit (events.js:116:17)

```
### Commands

```
     -9:34.3 command-palette:toggle (atom-text-editor.editor.is-focused)
  3x -9:17.8 meteor-helper:reset (atom-text-editor.editor.is-focused)
  2x -5:47.5 meteor-helper:toggle (atom-text-editor.editor.is-focused)
     -4:56.3 command-palette:toggle (atom-text-editor.editor.is-focused)
     -4:12.8 editor:consolidate-selections (atom-text-editor.editor.mini)
     -4:12.8 core:cancel (atom-text-editor.editor.mini)
     -1:17.3 core:confirm (atom-text-editor.editor.mini)
     -0:01.4 term2:open (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "language-javascript",
      "language-objective-c",
      "autocomplete-atom-api",
      "minimap"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-handlebars, v0.5.0
autocomplete-css, v0.7.2
autocomplete-html, v0.7.2
autocomplete-snippets, v1.7.0
bootstrap3-snippets, v0.1.2
color-picker, v2.0.7
linter, v0.12.7
linter-handlebars, v0.1.1
meteor-api, v2.19.0
meteor-helper, v0.21.0
term2, v0.9.15

# Dev
No dev packages
```

**Comment by MoOx** [comment]
You forget to insert the steps...

**Comment by BuZZ-dEE** [comment]
I also get this error if I toggle: `Term2: Pipe Path`

**Comment by f** [comment]
What are the steps? :/

**Comment by nbellowe** [comment]
Don't know about the steps, but I am getting this same error.

**Comment by nbellowe** [comment]
1. Hit "Term 2: Update"
2. See crash

**Atom Version**: 0.185.0-115f519
**System**: Mac OS X 10.10
**Thrown From**: 'nbellowe' package, vundefined

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/nbellowe/.atom/packages/term2/lib/TermView.coffee:142

TypeError: undefined is not a function
  at TermView.attachResizeEvents (/Users/nbellowe/.atom/packages/term2/lib/TermView.coffee:142:36)
  at TermView.attachEvents (/Users/nbellowe/.atom/packages/term2/lib/TermView.coffee:117:6)
  at TermView.initialize (/Users/nbellowe/.atom/packages/term2/lib/TermView.coffee:68:6)
  at TermView.View (/Applications/Editors/Text/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new TermView (/Users/nbellowe/.atom/packages/term2/lib/TermView.coffee:36:5)
  at Object.module.exports.createTermView (/Users/nbellowe/.atom/packages/term2/index.coffee:137:22)
  at Object.module.exports.splitTerm (/Users/nbellowe/.atom/packages/term2/index.coffee:145:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Editors/Text/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Editors/Text/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Editors/Text/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Editors/Text/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Editors/Text/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Editors/Text/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Editors/Text/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Editors/Text/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Editors/Text/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Editors/Text/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
     -0:15.0 project-manager:toggle (atom-pane.pane.active)
     -0:13.7 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:13.7 core:cancel (atom-text-editor.editor.mini)
     -0:13.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-material-ui)
  9x -0:11.3 core:move-down (atom-text-editor.editor.mini)
  5x -0:10.3 core:move-up (atom-text-editor.editor.mini)
     -0:05.2 core:confirm (atom-text-editor.editor.mini)
     -0:05.2 term2:open-split-right (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-material-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-dark-syntax"
    ],
    "projectHome": "/Users/nbellowe/Programming",
    "disabledPackages": [
      "welcome"
    ],
    "followSymlinks": true
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-material-ui, v0.6.0
atom-typescript, v4.5.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.7.1
file-icons, v1.6.9
highlight-selected, v0.10.1
language-scala, v1.1.3
linter, v1.4.3
linter-scalac, v1.0.2
linter-tslint, v0.4.0
linter-write-good, v0.6.1
minimap, v4.10.0
minimap-autohide, v0.10.1
minimap-bookmarks, v0.1.0
minimap-codeglance, v0.0.6
minimap-find-and-replace, v4.3.0
minimap-highlight-selected, v4.3.0
minimap-linter, v1.0.0
minimap-pigments, v0.1.6
minimap-selection, v4.3.0
nbellowe, vundefined
project-manager, v1.15.8
term2, v0.9.20

# Dev
No dev packages
```

**Comment by isurunix** [comment]
[Enter steps to reproduce below:]

1. Ctrl + Shift + P
2. Select term2:open

**Atom Version**: 0.184.0
**System**: linux 3.13.0-65-generic
**Thrown From**: [term2](https://github.com/f/atom-term2) package, v0.9.20

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/isuru/.atom/packages/term2/lib/TermView.coffee:142

TypeError: undefined is not a function
  at TermView.attachResizeEvents (/home/isuru/.atom/packages/term2/lib/TermView.coffee:142:36)
  at TermView.attachEvents (/home/isuru/.atom/packages/term2/lib/TermView.coffee:117:6)
  at TermView.initialize (/home/isuru/.atom/packages/term2/lib/TermView.coffee:68:6)
  at TermView.View (/usr/share/atom/resources/app/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new TermView (/home/isuru/.atom/packages/term2/lib/TermView.coffee:36:5)
  at Object.module.exports.createTermView (/home/isuru/.atom/packages/term2/index.coffee:137:22)
  at Object.module.exports.newTerm (/home/isuru/.atom/packages/term2/index.coffee:175:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
     -37:32.7 core:backspace (atom-text-editor.editor)
     -37:31.8 core:delete (atom-text-editor.editor)
     -37:31.2 core:backspace (atom-text-editor.editor)
     -37:30.5 core:move-right (atom-text-editor.editor)
     -37:30.0 core:move-down (atom-text-editor.editor)
     -37:28.4 pane:show-previous-item (atom-text-editor.editor)
     -37:27.5 pane:show-next-item (atom-text-editor.editor)
     -37:26.4 core:save (atom-text-editor.editor)
     -33:38.8 settings-view:open (atom-text-editor.editor)
     -33:27.2 core:confirm (atom-text-editor.editor.mini)
     -30:23.5 settings-view:open (atom-text-editor.editor)
     -30:06.7 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-numix-syntax.theme-atom-material-ui)
     -30:03.5 core:move-down (atom-text-editor.editor.mini)
     -30:03.2 core:move-up (atom-text-editor.editor.mini)
     -30:02.9 core:confirm (atom-text-editor.editor.mini)
     -30:02.9 term2:open (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-numix-syntax.theme-atom-material-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "archive-view",
      "tool-bar",
      "tool-bar-main"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-numix-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-numix-syntax, v0.2.1
atom-material-ui, v0.6.2
term2, v0.9.20

# Dev
No dev packages
```
