### ISSUE TITLE
Uncaught ReferenceError: isMac is not defined

### ISSUE THREAD

**Issue by jakesankey** [f/atom-term2#178]
[Enter steps to reproduce below:]
1. hit `cmd-k`
2. ...

**Atom Version**: 1.0.9
**System**: Mac OS X 10.10.4
**Thrown From**: [term2](https://github.com/f/atom-term2) package, v0.9.20
### Stack Trace

Uncaught ReferenceError: isMac is not defined

```
At /Users/js91162/.atom/packages/term2/node_modules/atom-term.js/src/term.js:2528

ReferenceError: isMac is not defined
  at Terminal.keyDown (/Users/js91162/.atom/packages/term2/node_modules/atom-term.js/src/term.js:2528:13)
  at HTMLDocument.<anonymous> (/Users/js91162/.atom/packages/term2/node_modules/atom-term.js/src/term.js:521:29)

```
### Commands

```
     -1:28.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:28.1.0 editor:delete-line (atom-text-editor.editor.is-focused)
     -1:27.8.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:27.4.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -1:27.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:26.7.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
  3x -1:26.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:23.9.0 core:save (atom-text-editor.editor.is-focused)
     -1:12.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:10.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:10 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:09.9.0 term2:open (atom-text-editor.editor)
     -1:07.0 pane:split-right-moving-current-tab (div.terminal)
     -0:33.7.0 core:confirm (div.terminal)
     -0:08.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:07.2.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".DS_Store",
      ".idea",
      ".com*",
      ".localized",
      "Thumbs.db",
      "target",
      "*.log",
      "*.iml",
      "*.log.1",
      "mocks",
      "embeddeddb*",
      "generated-sources",
      "tags",
      ".tags_swap",
      "node_modules",
      "velocity.log*"
    ],
    "followSymlinks": true,
    "disabledPackages": [
      "atom-jshint",
      "coffee-lint",
      "feedback",
      "metrics",
      "Sublime-Style-Column-Selection",
      "pulsing-cursor",
      "autocomplete-plus-async",
      "terminal-panel",
      "autocomplete",
      "symbols-tree-view",
      "sublime-tabs",
      "open-last-project",
      "deprecation-cop",
      "project-settings",
      "coffee-links",
      "git-blame-plus",
      "git-tab-status",
      "spec-maker",
      "linter-jshint",
      "linter-javac",
      "linter-coffeelint",
      "linter-scalac",
      "spell-check",
      "code-links"
    ],
    "projectHome": "/Users/js91162/Developer",
    "themes": [
      "nucleus-dark-ui",
      "one-dark-syntax"
    ]
  },
  "term2": {}
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.11
auto-detect-indentation, v0.4.2
autocomplete-paths, v1.0.2
block-travel, v1.0.2
coffee-compile, v0.18.0
color-picker, v2.0.11
expand-region, v0.2.3
file-icons, v1.6.9
foldingtext-for-atom, v0.9.0
git-log, v0.4.1
highlight-selected, v0.10.1
language-ejs, v0.2.0
language-groovy, v0.4.0
language-java, v0.16.0
language-scala, v1.1.3
language-swift, v0.4.0
language-velocity, v0.1.1
last-cursor-position, v0.9.0
line-diff-details, v1.1.2
linter, v1.4.3
minimap, v4.13.2
minimap-bookmarks, v0.1.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.0
nucleus-dark-ui, v0.2.4
pain-split, v1.4.0
pdf-view, v0.23.0
react, v0.12.6
resize-indent, v0.2.1
symbol-gen, v1.0.0
term2, v0.9.20
test-status, v0.35.0
white-cursor, v0.6.0

# Dev
No dev packages
```

**Comment by mmckegg** [comment]
It's happening for me whenever I press `K` regardless of whether `Cmd` is held or not.

**Comment by layonferreira** [comment]
I need to press cmd + k for the error to be thrown

**Comment by vlsd** [comment]
@mmckegg your PR fixed it for me. Thanks!

**Comment by dander401** [comment]
This also happens to me when i press k

**Comment by tylerFowler** [comment]
+1 on this (haven't tried the mentioned PR yet though)

**Comment by unloop** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: [term2](https://github.com/f/atom-term2) package, v0.9.20


### Stack Trace

Uncaught ReferenceError: isMac is not defined

```
At /Users/konstantin/.atom/packages/term2/node_modules/atom-term.js/src/term.js:2528

ReferenceError: isMac is not defined
  at Terminal.keyDown (/Users/konstantin/.atom/packages/term2/node_modules/atom-term.js/src/term.js:2528:13)
  at HTMLDocument.<anonymous> (/Users/konstantin/.atom/packages/term2/node_modules/atom-term.js/src/term.js:521:29)

```

### Commands

```
     -2:29.9.0 core:confirm (div.terminal)
  2x -2:28.4.0 core:move-up (div.terminal)
     -2:27.4.0 core:move-down (div.terminal)
     -2:26.1.0 core:confirm (div.terminal)
     -1:43 term2:open (atom-text-editor.editor.is-focused)
     -1:38.7.0 core:move-up (div.terminal)
     -1:38.1.0 core:confirm (div.terminal)
     -1:30.3.0 core:backspace (atom-text-editor#term2.fontSize.editor.mini.is-focused)
     -1:29.7.0 core:confirm (atom-text-editor#term2.fontSize.editor.mini.is-focused)
  2x -1:21 term2:open (atom-text-editor.editor.is-focused)
     -1:06.6.0 core:backspace (atom-text-editor#term2.fontFamily.editor.mini.is-focused)
     -0:57.7.0 term2:open-split-right (atom-pane.pane.active)
 19x -0:17.7.0 core:backspace (div.terminal)
     -0:06.4.0 core:confirm (div.terminal)
     -0:04.8.0 core:move-up (div.terminal)
     -0:04.3.0 core:confirm (div.terminal)
```

### Config

```json
{
  "core": {},
  "term2": {
    "fontSize": "12",
    "openPanesInSameSplit": true
  }
}
```

### Installed Packages

```coffee
# User
term2, v0.9.20

# Dev
No dev packages
```

**Comment by arisAlexis** [comment]
It happens on Linux mint 17 too

**Comment by ethe** [comment]
same as me

**Comment by darol100** [comment]
I still got this same error. Every time, I click 'k'.

**Comment by fredguth** [comment]
same here

**Comment by mmckegg** [comment]
@f: This pull request for a sub module fixes the bug - https://github.com/f/atom-term.js/pull/4

**Comment by netvl** [comment]
This happens for me every time I open the terminal in atom on my archlinux.

**Comment by szhu** [comment]
Took me a while to figure out how to apply the patch, so here it is reproduced below:

```shell
cd ~/.atom/packages/term2/node_modules
rm -rf atom-term.js
git clone https://github.com/mmckegg/atom-term.js.git atom-term.js
cd atom-term.js
git checkout patch-1
```

… then reload the Atom view or restart Atom.

**Comment by darol100** [comment]
@szhu ,

Thank you so much for your instruction. I can confirm that this fix the annoy 'K' problem.

**Comment by asiniy** [comment]
+1 is there any patch?

**Comment by szhu** [comment]
There is indeed a patch, but it has not been merged yet so you will not be able to install it through the package manager.  [My comment above](https://github.com/f/atom-term2/issues/178#issuecomment-140169752) shows you how to apply the patch.

**Comment by asiniy** [comment]
oh, ok. Thanks!

**Comment by jolson88** [comment]
Thanks szhu! Works great on my machine. This felt like a blocker for me to try out Atom (doing lots of docker stuff in term2, it's a bit of a pain for the error to pop up every time I hit "k" :P).

**Comment by KylePDavis** [comment]
+1 - Fixes annoying popup whenever I hit `k` on Mac OS X (f/atom-term2/issues/178) for me too!

**Comment by leov2000** [comment]
@szhu you're a legend. thanks

**Comment by Peterortiz82** [comment]
👍  @szhu
