### ISSUE TITLE
term2 0.9.20 cannot be loaded in latest Atom Version

### ISSUE THREAD

**Issue by Techro-Raj** [f/atom-term2#186]
The term2 package fails to rebuild in the latest version of atom (1.0.15). 

<img width="877" alt="screen shot 2015-09-19 at 9 36 10 pm" src="https://cloud.githubusercontent.com/assets/11791254/9978935/7f5f9890-5f16-11e5-819f-e4516e40135b.png">

Whenever I try to run, the error message is: 
```
Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.


gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 69
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/ashwinjeyaseelan/.atom/packages/term2/node_modules/pty.js
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 

npm ERR! Darwin 14.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/ashwinjeyaseelan/.atom/.apm/.apmrc" "--userconfig" "/Users/ashwinjeyaseelan/.atom/.apmrc" "rebuild" "--target=0.30.6" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE
npm ERR! pty.js@0.2.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.13 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ashwinjeyaseelan/.atom/packages/term2/npm-debug.log
```

**Comment by Techro-Raj** [comment]
For any OS X users who updated the latest version of X Code, you just need to open XCode and accept the agreement. Otherwise, the script build is working.

**Comment by varemenos** [comment]
This happens in Linux distros too so I'm not sure it's related to XCode...
