### ISSUE TITLE
Uncaught ReferenceError: isMac is not defined

### ISSUE THREAD

**Issue by renaudin** [f/atom-term2#190]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.15
**System**: Ubuntu 15.04
**Thrown From**: [term2](https://github.com/f/atom-term2) package, v0.9.20
### Stack Trace

Uncaught ReferenceError: isMac is not defined

```
At /home/renaudin/.atom/packages/term2/node_modules/atom-term.js/src/term.js:2528

ReferenceError: isMac is not defined
  at Terminal.keyDown (/home/renaudin/.atom/packages/term2/node_modules/atom-term.js/src/term.js:2528:13)
  at HTMLDocument.<anonymous> (/home/renaudin/.atom/packages/term2/node_modules/atom-term.js/src/term.js:521:29)

```
### Commands

```
     -2:21.8.0 term2:open (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-nucleus-dark-ui)
     -2:21 pane:show-previous-item (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-nucleus-dark-ui)
     -2:15.9.0 core:close (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-nucleus-dark-ui)
     -2:09.4.0 core:backspace (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-nucleus-dark-ui)
  2x -2:08.4.0 core:confirm (div.terminal)
     -2:03.1.0 core:backspace (div.terminal)
  3x -2:02.8.0 core:confirm (div.terminal)
  5x -1:22.1.0 core:backspace (div.terminal)
     -1:17.4.0 core:confirm (div.terminal)
     -1:14 core:backspace (div.terminal)
  2x -1:07.2.0 core:confirm (div.terminal)
 16x -0:55.6.0 core:backspace (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-nucleus-dark-ui)
  2x -0:44.7.0 core:confirm (div.terminal)
  5x -0:14.2.0 core:backspace (div.terminal)
     -0:03.1.0 core:confirm (div.terminal)
```
### Config

``` json
{
  "core": {
    "themes": [
      "nucleus-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "metrics"
    ],
    "autoHideMenuBar": true
  },
  "term2": {
    "colors": {
      "background": {
        "red": 209,
        "green": 214,
        "blue": 214,
        "alpha": 1
      },
      "foreground": {
        "red": 126,
        "green": 141,
        "blue": 150,
        "alpha": 1
      },
      "brightWhite": {
        "red": 252,
        "green": 252,
        "blue": 250,
        "alpha": 1
      },
      "normalWhite": {
        "red": 255,
        "green": 255,
        "blue": 255,
        "alpha": 1
      },
      "brightBlack": {
        "red": 0,
        "green": 0,
        "blue": 0,
        "alpha": 1
      },
      "normalBlack": {
        "red": 5,
        "green": 5,
        "blue": 5,
        "alpha": 1
      },
      "normalCyan": {
        "red": 0,
        "green": 125,
        "blue": 176,
        "alpha": 1
      },
      "normalGreen": {
        "red": 6,
        "green": 117,
        "blue": 29,
        "alpha": 1
      },
      "brightGreen": {
        "red": 72,
        "green": 185,
        "blue": 82,
        "alpha": 1
      }
    },
    "fontSize": "15",
    "titleTemplate": "Atom-Terminal (zsh)",
    "fontFamily": "Ubuntu Mono"
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-python, v0.5.3
file-icons, v1.6.9
language-latex, v0.6.1
latex, v0.25.1
linter, v1.6.0
minimap, v4.13.3
nucleus-dark-ui, v0.4.5
pdf-view, v0.25.0
remote-edit, v1.8.19
term2, v0.9.20

# Dev
No dev packages
```

**Comment by OJFord** [comment]
I also get this, but unlike above my `isMac` should be `true`.

(i.e. this issue occurs on both Macs and non-Macs)

**Comment by renaudin** [comment]
The error always happens when I press the 'k' on my keyboard.

**Comment by bkcsoft** [comment]
Here's a patch to fix the issue:
```
--- term2/node_modules/atom-term.js/src/term.js	2015-09-24 18:25:47.136379656 +0200
+++ term2/node_modules/atom-term.js/src/term.js	2015-09-24 18:20:48.783910942 +0200
@@ -2525,10 +2525,11 @@
       break;
     // CTRL-K
     case 75:
-      if ((!isMac && ev.ctrlKey) || (isMac && ev.metaKey)) {
+      if ((!this.isMac && ev.ctrlKey) || (this.isMac && ev.metaKey)) {
         this.clear();
         return cancel(ev);
       }
+      break;
     // F1
     case 112:
       key = '\x1bOP';
```
It's not an issue with atom-term2 itself but with 'term.js', point me to the right repo and I'll send a PR there :) (and reference here of course)

**Comment by seansellek** [comment]
@bkcsoft This works great, thank you!

Here's the repo you can open a PR at: https://github.com/f/atom-term.js

**Comment by bkcsoft** [comment]
@seansellek apparently ot's been fixed for 25days, just that the repo-owner havn't merged it yet... (The woes of dependencies :rolleyes: )

**Comment by OJFord** [comment]
@bkcsoft Which version is fixed? f/atom-term.js fork is on v0.0.55, original chjj/term.js is on v0.0.7, but [the dependency here](https://github.com/f/atom-term2/blob/master/package.json#L21) is v0.0.56?!

**Comment by carlosbaraza** [comment]
:+1:

**Comment by bkcsoft** [comment]
@OJford it havn't been merged yet. There is an open PR withbthe exact same patch, just that it isn't merged :)

**Comment by erikanderson** [comment]
+1 for merging in the fix

**Comment by ron-wolf** [comment]
Happens to me whenever I resize the window. Running OS X 10.11. Will try patch.

**Comment by wonderbeyond** [comment]
+1

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Ubuntu 14.04.3
**Thrown From**: [term2](https://github.com/f/atom-term2) package, v0.9.20


### Stack Trace

Uncaught ReferenceError: isMac is not defined

```
At /home/wonder/.atom/packages/term2/node_modules/atom-term.js/src/term.js:2528

ReferenceError: isMac is not defined
  at Terminal.keyDown (/home/wonder/.atom/packages/term2/node_modules/atom-term.js/src/term.js:2528:13)
  at HTMLDocument.<anonymous> (/home/wonder/.atom/packages/term2/node_modules/atom-term.js/src/term.js:521:29)

```

### Commands

```
     -5:43 command-palette:toggle (atom-text-editor.editor.is-focused)
     -5:34 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -5:34 core:cancel (atom-text-editor.editor.mini.is-focused)
     -5:31.5.0 term2:open (atom-text-editor.editor.is-focused)
     -5:27.5.0 core:confirm (div.terminal)
  2x -5:10.8.0 core:backspace (div.terminal)
  7x -4:52.4.0 core:confirm (div.terminal)
     -3:45 core:close (div.terminal)
     -3:42.8.0 pane:split-right (atom-text-editor.editor.is-focused)
     -3:40.6.0 core:close (atom-text-editor.editor.is-focused)
     -3:37.3.0 term2:open (atom-text-editor.editor.is-focused)
     -3:32.8.0 core:move-down (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-atom-dark-ui)
     -3:27.1.0 term2:open (atom-text-editor.editor.is-focused)
  8x -2:53 core:confirm (div.terminal)
  3x -2:14.7.0 window:increase-font-size (div.terminal)
 19x -2:08.1.0 core:confirm (div.terminal)
```

### Config

```json
{
  "core": {
    "projectHome": "/home/wonder/projects",
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "term2": {}
}
```

### Installed Packages

```coffee
# User
emmet-simplified, v2.5.0
image-view, v0.55.0
minimap, v4.13.3
term2, v0.9.20

# Dev
No dev packages
```

**Comment by ahmet** [comment]
+1 for the patch @f

**Comment by javinc** [comment]
https://github.com/f/atom-term2/issues/178#issuecomment-139842506
