### ISSUE TITLE
Installing “term2@0.9.21” failed

### ISSUE THREAD

**Issue by wonderbeyond** [f/atom-term2#197]
Atom version: 1.0.19
Platform: Ubuntu 12.04.5 LTS

```
> pty.js@0.2.13 install /tmp/apm-install-dir-11598-12889-101pwbo/node_modules/term2/node_modules/pty.js
> node-gyp rebuild

make:进入目录'/tmp/apm-install-dir-11598-12889-101pwbo/node_modules/term2/node_modules/pty.js/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
make:离开目录“/tmp/apm-install-dir-11598-12889-101pwbo/node_modules/term2/node_modules/pty.js/build”

In file included from /home/wonder/.atom/.node-gyp/.node-gyp/0.30.7/src/node.h:42:0,
                 from ../node_modules/nan/nan.h:24,
                 from ../src/unix/pty.cc:20:
/home/wonder/.atom/.node-gyp/.node-gyp/0.30.7/deps/v8/include/v8.h:543:1: 错误： expected unqualified-id before ‘using’
/home/wonder/.atom/.node-gyp/.node-gyp/0.30.7/deps/v8/include/v8.h:922:1: 错误： expected unqualified-id before ‘using’
../src/unix/pty.cc: 在函数‘void PtyFork(const v8::FunctionCallbackInfo<v8::Value>&)’中:
../src/unix/pty.cc:227:34: 警告： 忽略声明有 warn_unused_result 属性的‘int chdir(const char*)’的返回值 [-Wunused-result]
make: *** [Release/obj.target/pty/src/unix/pty.o] 错误 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-64-generic
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-11598-12889-101pwbo/node_modules/term2/node_modules/pty.js
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 3.13.0-64-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/wonder/.atom/.apm/.apmrc" "--userconfig" "/home/wonder/.atom/.apmrc" "install" "/tmp/d-11598-12889-1dntbru/package.tgz" "--target=0.30.7" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.13 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11598-12889-101pwbo/npm-debug.log
```

**Comment by helloncanella** [comment]
same here

**Comment by wonderbeyond** [comment]
Still unresolved

**Comment by axsk** [comment]
same for me on windows

**Comment by rwatts3** [comment]
confirmed on windows ?

**Comment by rattrayalex** [comment]
same here on OSX

**Comment by rattrayalex** [comment]
https://github.com/Floobits/atom-term3 seems to have fixed this, I switched to that package and it's working.

**Comment by AnikaJaffara** [comment]
Wow... same here... tried Term3... decided to try Term2 again with a manual install... still nothing.

**Comment by ivorscott** [comment]
Thanks rattrayalex. Term3 will do.

**Comment by calebhaye** [comment]
term3 is working for me.. thx @rattrayalex 💪

**Comment by xgt001** [comment]
same issue on OSX 10.11.4 as well.

**Comment by Zamicol** [comment]
+1 Using Linux Mint 17.3 Rosa.

**Comment by mrichman** [comment]
+1 using Ubuntu 16.04 LTS (Xenial)

**Comment by ajyoon** [comment]
+1 on Ubuntu 14.04 LTS :(
