### ISSUE TITLE
Installing “term2@0.9.21” failed on Atom 1.3.2

### ISSUE THREAD

**Issue by weijiahan** [f/atom-term2#218]
OSX 10.11.2

```
> pty.js@1.2.13 install /private/var/folders/m7/n77l044j1fs7lpxhl8lym34h0000gn/T/apm-install-dir-1151127-40361-1wophyy/node_modules/term2/node_modules/pty.js
> node-gyp rebuild

  CXX(target) Release/obj.target/pty/src/unix/pty.o

2015-12-27 19:04:13.054 xcodebuild[40371:4947353] ### Failed to load Addressbook class CNContactNameFormatter
In file included from ../src/unix/pty.cc:20:
../node_modules/nan/nan.h:324:27: error: redefinition of 'NanEnsureHandleOrPersistent'
  NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                          ^
../node_modules/nan/nan.h:319:17: note: previous definition is here
  v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                ^
../node_modules/nan/nan.h:344:27: error: redefinition of 'NanEnsureLocal'
  NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                          ^
../node_modules/nan/nan.h:334:27: note: previous definition is here
  NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                          ^
../node_modules/nan/nan.h:757:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:768:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/weijh/.atom/.node-gyp/.node-gyp/0.34.3/src/node_buffer.h:41:40: note: candidate function not viable: no known conversion from 'uint32_t' (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/weijh/.atom/.node-gyp/.node-gyp/0.34.3/src/node_buffer.h:53:40: note: candidate function not viable: 2nd argument ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/weijh/.atom/.node-gyp/.node-gyp/0.34.3/src/node_buffer.h:38:40: note: candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/weijh/.atom/.node-gyp/.node-gyp/0.34.3/src/node_buffer.h:46:40: note: candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../src/unix/pty.cc:20:
../node_modules/nan/nan.h:772:12: error: no viable conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/weijh/.atom/.node-gyp/.node-gyp/0.34.3/deps/v8/include/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/weijh/.atom/.node-gyp/.node-gyp/0.34.3/deps/v8/include/v8.h:210:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
class Local {
      ^
/Users/weijh/.atom/.node-gyp/.node-gyp/0.34.3/deps/v8/include/v8.h:214:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/weijh/.atom/.node-gyp/.node-gyp/0.34.3/deps/v8/include/v8.h:326:13: note: candidate template ignored: could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../src/unix/pty.cc:20:
../node_modules/nan/nan.h:779:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
In file included from ../src/unix/pty.cc:20:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/weijh/.atom/.node-gyp/.node-gyp/0.34.3/src/node.h:42:
/Users/weijh/.atom/.node-gyp/.node-gyp/0.34.3/deps/v8/include/v8.h:221:5: error: assigning to 'v8::Primitive *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/weijh/.atom/.node-gyp/.node-gyp/0.34.3/deps/v8/include/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:501:12: note: in instantiation of function template specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             ^
In file included from ../src/unix/pty.cc:20:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/weijh/.atom/.node-gyp/.node-gyp/0.34.3/src/node.h:42:
/Users/weijh/.atom/.node-gyp/.node-gyp/0.34.3/deps/v8/include/v8.h:221:5: error: assigning to 'v8::Boolean *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/weijh/.atom/.node-gyp/.node-gyp/0.34.3/deps/v8/include/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:511:12: note: in instantiation of function template specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             ^
In file included from ../src/unix/pty.cc:20:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/weijh/.atom/.node-gyp/.node-gyp/0.34.3/src/node.h:42:
/Users/weijh/.atom/.node-gyp/.node-gyp/0.34.3/deps/v8/include/v8.h:221:5: error: assigning to 'v8::Function *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/weijh/.atom/.node-gyp/.node-gyp/0.34.3/deps/v8/include/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1645:12: note: in instantiation of function template specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             ^
In file included from ../src/unix/pty.cc:20:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/weijh/.atom/.node-gyp/.node-gyp/0.34.3/src/node.h:42:
/Users/weijh/.atom/.node-gyp/.node-gyp/0.34.3/deps/v8/include/v8.h:221:5: error: assigning to 'v8::Object *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/weijh/.atom/.node-gyp/.node-gyp/0.34.3/deps/v8/include/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1776:12: note: in instantiation of function template specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(
           ^
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             ^
10 errors generated.
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error 

gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/m7/n77l044j1fs7lpxhl8lym34h0000gn/T/apm-install-dir-1151127-40361-1wophyy/node_modules/term2/node_modules/pty.js
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 15.2.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/weijh/.atom/.apm/.apmrc" "--userconfig" "/Users/weijh/.atom/.apmrc" "install" "/private/var/folders/m7/n77l044j1fs7lpxhl8lym34h0000gn/T/d-1151127-40361-1g18xck/package.tgz" "--target=0.34.3" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.13 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/m7/n77l044j1fs7lpxhl8lym34h0000gn/T/apm-install-dir-1151127-40361-1wophyy/npm-debug.log
```

**Comment by PuYart** [comment]
+1

**Comment by bluemsn** [comment]
+1

**Comment by raingloom** [comment]
+ plus 1

**Comment by andysaini** [comment]
similar issue on arch linux!

**Comment by sidhuko** [comment]
+1 on OS X

**Comment by felixhammerl** [comment]
+1 on OS X

**Comment by pixelize** [comment]
same here Atom 1.3.2 - osx 10.10.4

**Comment by mikemackintosh** [comment]
+1

atom 1.3.2

```
ProductName:	Mac OS X
ProductVersion:	10.11.2
BuildVersion:	15C50
```

**Comment by aldendaniels** [comment]
+1 on atom 1.4.0-beta

**Comment by jergason** [comment]
While waiting for this to be resolved I've switched to
https://github.com/Floobits/atom-term3, which installs fine.

**Comment by bruinebeer** [comment]
@jergason nice, i switched too, any reason why you would switch back? feels like this package does enough..

**Comment by arthow4n** [comment]
a workaround inspired by this, worked on Ubuntu 14.04:
https://github.com/petethepig/devtools-terminal/issues/41#issuecomment-50264402

1. mkdir /tmp/pty.js
2. git clone https://github.com/chjj/pty.js.git /tmp/pty.js
3. vi /tmp/pty.js/src/unix/pty.cc
4. replace line 39: #include <util.h> with #include "/usr/include/util.h"

5. git clone https://github.com/f/atom-term2.git
6. cd atom-term2
7. vi ./package.json #and replace "pty.js": "^0.2.13" with the version of pty.js which you cloned from in step 2, currently works with pty.js of version 0.3.0
8. npm install
9. apm link

and term2 should be working now

**Comment by sikhote** [comment]
+1 on OS X

**Comment by smustard** [comment]
+1

@jergason worked great for me. Cheers

**Comment by Darkking122** [comment]
+1

**Comment by itsazzad** [comment]
Failing with me as well @Atom-1.4.1

**Comment by andysaini** [comment]
failing for me too @atom latest(1.4.1)

**Comment by drawcard** [comment]
Problem here too

**Comment by NicoHood** [comment]
I think we should stop writing "+1" or such. everyone noticed that it affects a lot of users and a lot of people want this to get fixed. But since there is no feedback we cant expect a fix the more you guys write "+1".

We should rather discuss the problem and try to fix it instead. Or someone could also suggest another addin that also works instead for atom. If the software is not maintained anymore it is possibly not worth to track it anymore and switch to something else.

So anyone got a working alternative?

**Comment by lorenzos** [comment]
@NicoHood I'm using [term3](https://atom.io/packages/term3).

**Comment by drawcard** [comment]
I was just reporting that the problem was happening on 1.4.2 which was new information.

**Comment by pjr314** [comment]
Same issue on atom 1.4.3 Mac OSX 10.11.3

Installing “term2@0.9.21” failed.Hide output…

> pty.js@0.2.13 install /private/var/folders/y7/7hh14sm10fz3r997dvpxfn880000gn/T/apm-install-dir-11615-1318-p4hof7/node_modules/term2/node_modules/pty.js
> node-gyp rebuild

  CXX(target) Release/obj.target/pty/src/unix/pty.o

In file included from ../src/unix/pty.cc:20:
../node_modules/nan/nan.h:324:27: error: redefinition of 'NanEnsureHandleOrPersistent'
  NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                          ^
../node_modules/nan/nan.h:319:17: note: previous definition is here
  v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                ^
../node_modules/nan/nan.h:344:27: error: redefinition of 'NanEnsureLocal'
  NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                          ^
../node_modules/nan/nan.h:334:27: note: previous definition is here
  NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                          ^
../node_modules/nan/nan.h:757:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:768:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/patrickreed/.atom/.node-gyp/.node-gyp/0.34.5/src/node_buffer.h:41:40: note: candidate function not viable: no known conversion from 'uint32_t' (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/patrickreed/.atom/.node-gyp/.node-gyp/0.34.5/src/node_buffer.h:53:40: note: candidate function not viable: 2nd argument ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/patrickreed/.atom/.node-gyp/.node-gyp/0.34.5/src/node_buffer.h:38:40: note: candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/patrickreed/.atom/.node-gyp/.node-gyp/0.34.5/src/node_buffer.h:46:40: note: candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../src/unix/pty.cc:20:
../node_modules/nan/nan.h:772:12: error: no viable conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/patrickreed/.atom/.node-gyp/.node-gyp/0.34.5/deps/v8/include/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/patrickreed/.atom/.node-gyp/.node-gyp/0.34.5/deps/v8/include/v8.h:210:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
class Local {
      ^
/Users/patrickreed/.atom/.node-gyp/.node-gyp/0.34.5/deps/v8/include/v8.h:214:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/patrickreed/.atom/.node-gyp/.node-gyp/0.34.5/deps/v8/include/v8.h:326:13: note: candidate template ignored: could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../src/unix/pty.cc:20:
../node_modules/nan/nan.h:779:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
In file included from ../src/unix/pty.cc:20:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/patrickreed/.atom/.node-gyp/.node-gyp/0.34.5/src/node.h:42:
/Users/patrickreed/.atom/.node-gyp/.node-gyp/0.34.5/deps/v8/include/v8.h:221:5: error: assigning to 'v8::Primitive *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/patrickreed/.atom/.node-gyp/.node-gyp/0.34.5/deps/v8/include/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:501:12: note: in instantiation of function template specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             ^
In file included from ../src/unix/pty.cc:20:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/patrickreed/.atom/.node-gyp/.node-gyp/0.34.5/src/node.h:42:
/Users/patrickreed/.atom/.node-gyp/.node-gyp/0.34.5/deps/v8/include/v8.h:221:5: error: assigning to 'v8::Boolean *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/patrickreed/.atom/.node-gyp/.node-gyp/0.34.5/deps/v8/include/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:511:12: note: in instantiation of function template specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             ^
In file included from ../src/unix/pty.cc:20:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/patrickreed/.atom/.node-gyp/.node-gyp/0.34.5/src/node.h:42:
/Users/patrickreed/.atom/.node-gyp/.node-gyp/0.34.5/deps/v8/include/v8.h:221:5: error: assigning to 'v8::Function *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/patrickreed/.atom/.node-gyp/.node-gyp/0.34.5/deps/v8/include/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1645:12: note: in instantiation of function template specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             ^
In file included from ../src/unix/pty.cc:20:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/patrickreed/.atom/.node-gyp/.node-gyp/0.34.5/src/node.h:42:
/Users/patrickreed/.atom/.node-gyp/.node-gyp/0.34.5/deps/v8/include/v8.h:221:5: error: assigning to 'v8::Object *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/patrickreed/.atom/.node-gyp/.node-gyp/0.34.5/deps/v8/include/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1776:12: note: in instantiation of function template specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(
           ^
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             ^
10 errors generated.
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error 

gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/y7/7hh14sm10fz3r997dvpxfn880000gn/T/apm-install-dir-11615-1318-p4hof7/node_modules/term2/node_modules/pty.js
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 15.3.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/patrickreed/.atom/.apm/.apmrc" "--userconfig" "/Users/patrickreed/.atom/.apmrc" "install" "/private/var/folders/y7/7hh14sm10fz3r997dvpxfn880000gn/T/d-11615-1318-1i5sm5j/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.13 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/y7/7hh14sm10fz3r997dvpxfn880000gn/T/apm-install-dir-11615-1318-p4hof7/npm-debug.log

**Comment by NicoHood** [comment]
cmon.... srly?

**Comment by pjr314** [comment]
@NicoHood +1 ....forgot to mention that

**Comment by shivam99aa** [comment]
Any update on this issue ?? Still unable to install term2 on ubuntu 14.04.

**Comment by gabortill** [comment]
+1 on OS X 10.11.4

**Comment by jonvargas** [comment]
Same issue. Ubuntu 16.04.

**Comment by holoto** [comment]
+1 on OS X 10.11.4

**Comment by holoto** [comment]
# 我解决这个问题了
# I've solved this problem.
# in mac osx 10.11.4
# in bash
`cd ~/.atom/packages/`
`git clone https://github.com/f/atom-term2.git`
`cd atom-term2`
`apm install `
`apm link `
##reboot you atom
##term2 can use !! start you code
